language: python
sudo: false

cache:
  directories:
    - ~/.cache/pip

python:
  - 3.6

install:
  - ls
  - cd mencionar_boy
  - python3 mencionar_boy.py

script:
  - nosetests --with-coverage

after_success:
  - coveralls
