#!/bin/bash
id=100
while true
do
        # Si hay un proceso abierto lo cerramos
    if (($id != 100))
    then
        screen kill $id
    fi
        
        # Guardamos la hora en formato HH
        hora=$(echo 10#$(date) | cut -d ":" -f 1 | cut -d " " -f 4)
        # Si el programa se acaba de arrancar o son las 5 am se clona el github
        if (($hora == 5 || $id == 100))
        then
                cd ~
                rm -rf mencionar_bot
                git clone https://github.com/Eloypripan/mencionar_bot
                chmod +x mencionar_bot.py
        fi
    
    screen -S Mencionador -d -m /home/bots/mencionar_bot/mencionar_bot.py
    id=$(screen -ls | grep Menciondor | cut -d '.' -f 1)
    date
    echo El programa se reiniciará en 55 minutos
    sleep 55m
done
